### ISSUE TITLE
Support for Language Detector API and Translator API

### ISSUE THREAD

**Issue by xmlking** [axonzeta/aibrow#1]
like chrome, any plans to add `Language Detector API` and `Translator API` to `aibrow` ?

**Comment by Thomas101** [comment]
We've done some experimentation here and we can add these in. Hopefully we can get it out next week sometime :)

**Comment by xmlking** [comment]
you guys rock!. thanks for quick support.

**Comment by Thomas101** [comment]
This is now live to try in version 1.2.0 of the extension and helper :)
