### ISSUE TITLE
typescript type definitions for aibrow

### ISSUE THREAD

**Issue by xmlking** [axonzeta/aibrow#2]
any plans to publish type definitions for `aibrow` like:
[@types/dom-chromium-ai](https://www.npmjs.com/package/@types/dom-chromium-ai)

<img width="661" alt="image" src="https://github.com/user-attachments/assets/dc86005e-57dc-4caf-8bf2-530e4a36c8c6">

**Comment by Thomas101** [comment]
Thanks, I've added this in https://github.com/axonzeta/aibrow/commit/5eac0a1e301fddfe890dd32c435eea43670858d5 and I'll publish them out in the next release, either today or early next week. Once they're published you should be able to use them by adding the following to the entry point of your app 👍

```ts
import type AI from "@aibrow/dom-types"
declare global {
  interface Window {
    readonly aibrow: typeof AI;
  }
}
```

**Comment by xmlking** [comment]
I like to use `window.ai.` namespace in my code, but still like to patch only specific models (e.g., `window.ai.writer` , `window.ai.rewriter`) with aibrow.  

Would be nice if we allow those customizations via aibrow chrome extension  settings. 

**Note:** today if I have `Writer API for Gemini Nano` flag enabled in `chrome://flags/` ,  `window.ai.` is always point to browserAI. 
we need setting to overwrite it.

**Comment by xmlking** [comment]
> Thanks, I've added this in [5eac0a1](https://github.com/axonzeta/aibrow/commit/5eac0a1e301fddfe890dd32c435eea43670858d5) and I'll publish them out in the next release, either today or early next week. Once they're published you should be able to use them by adding the following to the entry point of your app 👍
> 
> ```ts
> import type AI from "@aibrow/dom-types"
> declare global {
>   interface Window {
>     readonly aibrow: typeof AI;
>   }
> }
> ```

for me WindowOrWorkerGlobalScope worked without vscode errors
```ts
import type AI from "@aibrow/dom-types"
declare global {
  interface WindowOrWorkerGlobalScope {
    readonly aibrow: typeof AI;
  }
}
  ```

**Comment by Thomas101** [comment]
Yep, I think that should be the same as `WindowOrWorkerGlobalScope` is a subtype of `Window`. We don't auto-inject to service workers at the moment - in fact I'm not sure on the best way to use the API through a service worker, that might be something to add in the future
