### ISSUE TITLE
type in docs window.ai.aibrow ?

### ISSUE THREAD

**Issue by xmlking** [axonzeta/aibrow#3]
wonder if `window.ai.aibrow` valid or type in docs 

https://docs.aibrow.ai/examples/detect-if-aibrow-is-installed#detect-if-aibrow-is-polyfilling-window.ai
<img width="845" alt="image" src="https://github.com/user-attachments/assets/19819eef-fd75-47a9-8e1e-3f3f82f95fa4">

**Comment by Thomas101** [comment]
`window.ai.aibrow` wouldn't be available in the type definitions as this case would only happen if AiBrow is polyfilling `window.ai` for browsers that don't support it yet (e.g. Firefox, Edge etc).

The polyfilled API should be compatible with the Chrome `window.ai` types, so if you don't know anything about aibrow, ai should just work as you expect - it's more there as a check for devs to see if it is being polyfilled.
