### ISSUE TITLE
how to uninstall On-device helper?

### ISSUE THREAD

**Issue by xmlking** [axonzeta/aibrow#5]
if I like to uninstall 
1. AiBrow Extension 
2. On-device helper 
4. 3. any extra models downloaded

 completely and reinstall, what are the steps I should follow?

removing Extension is not uninstalling On-device helper  currently

**Comment by Thomas101** [comment]
If you want to remove models, the easiest way is to click on the AiBrow extension in the top-right of Chrome, then under the models section remove the ones you no longer want.

If you want to remove the helper and models completely, removing its data directory will do this. It's located at

* macOS `~/Library/Application Support/Axonzeta/AiBrow`
* Windows `~/AppData/Local/Axonzeta/AiBrow`
* Linux `~/.config/Axonzeta/AiBrow

**Comment by Thomas101** [comment]
I've added this to the docs too https://docs.aibrow.ai/guides/remove-the-on-device-helper-or-models
